[package]
name = "RustRocket"
version = "0.1.0"
edition = "2018"

[dependencies]
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
gtk = "0.9.0"
gio = "0.9.0"
chrono = "0.4"
once_cell = "1.8.0"
glib = "0.10.3"
dirs = "3.0"
xdg = "2.2.0"

