[package]
name = "waylaunch"
version = "0.1.0"
edition = "2018"

[dependencies]
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
gtk = "0.9.0"
gio = "0.9.0"
chrono = "0.4"
lazy_static = "1.4.0"
once_cell = "1.8.0"
glib = "0.10.3"
rayon = "1.5.3"

